from sqlalchemy import (
    Column, Integer, String, Float, Date, DateTime,
    Boolean, ForeignKey, Text, UniqueConstraint
)
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func
from database.db import Base


class User(Base):
    __tablename__ = "users"
    id               = Column(Integer, primary_key=True, index=True)
    staff_no         = Column(String(20), unique=True, index=True, nullable=False)
    name             = Column(String(100), nullable=False)
    mobile           = Column(String(20), index=True)
    designation      = Column(String(100))
    designation_code = Column(String(20))
    dp_code          = Column(String(20))
    section          = Column(String(100))
    zone             = Column(String(100))
    basic_pay        = Column(Float, default=0.0)
    home_state       = Column(String(60), default="Maharashtra")
    city_category    = Column(String(10), default="B1")
    email            = Column(String(150), unique=True)
    hashed_password  = Column(String(255), nullable=False)
    is_active        = Column(Boolean, default=True)
    is_admin         = Column(Boolean, default=False)
    created_at       = Column(DateTime, server_default=func.now())
    address_line1    = Column(String(200))
    address_line2    = Column(String(200))
    city_pin         = Column(String(100))
    bank_name        = Column(String(100))
    bank_account_no  = Column(String(50))
    ta_id            = Column(String(50))

    monthly_diaries    = relationship("MonthlyDiary",     back_populates="user", cascade="all, delete-orphan")
    attendance_records = relationship("AttendanceRecord", back_populates="user", cascade="all, delete-orphan")
    travel_legs        = relationship("TravelLeg",        back_populates="user", cascade="all, delete-orphan")
    hotel_stays        = relationship("HotelStay",        back_populates="user", cascade="all, delete-orphan")
    local_conveyances  = relationship("LocalConveyance",  back_populates="user", cascade="all, delete-orphan")
    other_expenses     = relationship("OtherExpense",     back_populates="user", cascade="all, delete-orphan")
    bills              = relationship("Bill",             back_populates="user", cascade="all, delete-orphan")


class MonthlyDiary(Base):
    __tablename__ = "monthly_diaries"
    __table_args__ = (UniqueConstraint("user_id", "month", "year"),)
    id            = Column(Integer, primary_key=True, index=True)
    user_id       = Column(Integer, ForeignKey("users.id"), nullable=False)
    month         = Column(Integer, nullable=False)
    year          = Column(Integer, nullable=False)
    bank_state    = Column(String(60))
    bank_gstin    = Column(String(20))
    status        = Column(String(20), default="draft")
    total_fare    = Column(Float, default=0.0)
    total_lodging = Column(Float, default=0.0)
    total_halting = Column(Float, default=0.0)
    total_local   = Column(Float, default=0.0)
    total_other   = Column(Float, default=0.0)
    total_gst     = Column(Float, default=0.0)
    grand_total   = Column(Float, default=0.0)
    created_at    = Column(DateTime, server_default=func.now())
    updated_at    = Column(DateTime, onupdate=func.now())

    user               = relationship("User",             back_populates="monthly_diaries")
    attendance_records = relationship("AttendanceRecord", back_populates="diary", cascade="all, delete-orphan")
    travel_legs        = relationship("TravelLeg",        back_populates="diary", cascade="all, delete-orphan")
    hotel_stays        = relationship("HotelStay",        back_populates="diary", cascade="all, delete-orphan")
    local_conveyances  = relationship("LocalConveyance",  back_populates="diary", cascade="all, delete-orphan")
    other_expenses     = relationship("OtherExpense",     back_populates="diary", cascade="all, delete-orphan")
    bills              = relationship("Bill",             back_populates="diary", cascade="all, delete-orphan")


class AttendanceRecord(Base):
    __tablename__ = "attendance_records"
    __table_args__ = (UniqueConstraint("diary_id", "duty_date"),)
    id                   = Column(Integer, primary_key=True, index=True)
    user_id              = Column(Integer, ForeignKey("users.id"), nullable=False)
    diary_id             = Column(Integer, ForeignKey("monthly_diaries.id"))
    duty_date            = Column(Date, nullable=False)
    branch_name          = Column(String(200))
    dp_code              = Column(String(20))
    audit_type           = Column(String(50))
    place                = Column(String(100))
    mandays_sanctioned   = Column(Integer, default=0)
    mandays_pending      = Column(Integer, default=0)
    mandays_utilised     = Column(Integer, default=0)
    executive_mandays    = Column(Integer, default=0)
    exec_mandays_pending = Column(Integer, default=0)
    date_of_commencement = Column(Date)
    is_holiday           = Column(Boolean, default=False)
    is_leave             = Column(Boolean, default=False)
    is_weekend           = Column(Boolean, default=False)
    duty_from_time       = Column(String(10), default="09:00")
    duty_to_time         = Column(String(10), default="18:00")
    source               = Column(String(20), default="whatsapp")
    raw_message          = Column(Text)
    is_duplicate         = Column(Boolean, default=False)
    needs_review         = Column(Boolean, default=False)
    review_note          = Column(Text)
    created_at           = Column(DateTime, server_default=func.now())

    user  = relationship("User",         back_populates="attendance_records")
    diary = relationship("MonthlyDiary", back_populates="attendance_records")


class Bill(Base):
    __tablename__ = "bills"
    id             = Column(Integer, primary_key=True, index=True)
    user_id        = Column(Integer, ForeignKey("users.id"), nullable=False)
    diary_id       = Column(Integer, ForeignKey("monthly_diaries.id"))
    file_name      = Column(String(255))
    file_path      = Column(String(500))
    file_type      = Column(String(10))
    bill_category  = Column(String(30))
    ocr_raw_text   = Column(Text)
    vendor_name    = Column(String(200))
    invoice_date   = Column(Date)
    invoice_number = Column(String(100))
    vendor_gstin   = Column(String(20))
    vendor_state   = Column(String(60))
    amount_exc_gst = Column(Float, default=0.0)
    gst_percent    = Column(Float, default=0.0)
    gst_amount     = Column(Float, default=0.0)
    total_amount   = Column(Float, default=0.0)
    is_verified    = Column(Boolean, default=False)
    is_matched     = Column(Boolean, default=False)
    uploaded_at    = Column(DateTime, server_default=func.now())

    user  = relationship("User",         back_populates="bills")
    diary = relationship("MonthlyDiary", back_populates="bills")


class TravelLeg(Base):
    __tablename__ = "travel_legs"
    id                        = Column(Integer, primary_key=True, index=True)
    user_id                   = Column(Integer, ForeignKey("users.id"), nullable=False)
    diary_id                  = Column(Integer, ForeignKey("monthly_diaries.id"))
    bill_id                   = Column(Integer, ForeignKey("bills.id"), nullable=True)
    from_place                = Column(String(100))
    to_place                  = Column(String(100))
    date_start                = Column(Date)
    time_start                = Column(String(10))
    date_arrival              = Column(Date)
    time_arrival              = Column(String(10))
    mode                      = Column(String(30))
    travel_class              = Column(String(20))
    distance_km               = Column(Float, default=0.0)
    claimed_amount_exc_gst    = Column(Float, default=0.0)
    gst_percent               = Column(Float, default=0.0)
    claimed_gst               = Column(Float, default=0.0)
    non_taxable               = Column(Float, default=0.0)
    total_amount              = Column(Float, default=0.0)
    vendor_state              = Column(String(60))
    vendor_gstin              = Column(String(20))
    bank_state                = Column(String(60))
    bank_gstin                = Column(String(20))
    ticket_no                 = Column(String(100))
    invoice_date              = Column(Date)
    invoice_number            = Column(String(100))
    no_bill                   = Column(Boolean, default=False)
    sanctioned_amount_exc_gst = Column(Float, default=0.0)
    sanctioned_gst            = Column(Float, default=0.0)
    amount_approved           = Column(Float, default=0.0)
    remarks                   = Column(Text)
    created_at                = Column(DateTime, server_default=func.now())

    user  = relationship("User",         back_populates="travel_legs")
    diary = relationship("MonthlyDiary", back_populates="travel_legs")
    bill  = relationship("Bill")


class HotelStay(Base):
    __tablename__ = "hotel_stays"
    id                     = Column(Integer, primary_key=True, index=True)
    user_id                = Column(Integer, ForeignKey("users.id"), nullable=False)
    diary_id               = Column(Integer, ForeignKey("monthly_diaries.id"))
    bill_id                = Column(Integer, ForeignKey("bills.id"), nullable=True)
    checkin_date           = Column(Date)
    checkin_time           = Column(String(10))
    checkout_date          = Column(Date)
    checkout_time          = Column(String(10))
    city                   = Column(String(100))
    hotel_name             = Column(String(200))
    hotel_type             = Column(String(20), default="ThreeStar")
    lodging_amount         = Column(Float, default=0.0)
    boarding_amount        = Column(Float, default=0.0)
    total_lb               = Column(Float, default=0.0)
    gst_percent            = Column(Float, default=12.0)
    claimed_gst            = Column(Float, default=0.0)
    vendor_state           = Column(String(60))
    vendor_gstin           = Column(String(20))
    bank_state             = Column(String(60))
    bank_gstin             = Column(String(20))
    invoice_date           = Column(Date)
    invoice_number         = Column(String(100))
    no_bill                = Column(Boolean, default=False)
    halting_allowance      = Column(Float, default=0.0)
    total_claimed_exc_gst  = Column(Float, default=0.0)
    declaration_amount     = Column(Float, default=0.0)
    declaration_text       = Column(Text)
    sanctioned_amount      = Column(Float, default=0.0)
    sanctioned_gst         = Column(Float, default=0.0)
    remarks                = Column(Text)
    created_at             = Column(DateTime, server_default=func.now())

    user  = relationship("User",         back_populates="hotel_stays")
    diary = relationship("MonthlyDiary", back_populates="hotel_stays")
    bill  = relationship("Bill")


class LocalConveyance(Base):
    __tablename__ = "local_conveyances"
    id                     = Column(Integer, primary_key=True, index=True)
    user_id                = Column(Integer, ForeignKey("users.id"), nullable=False)
    diary_id               = Column(Integer, ForeignKey("monthly_diaries.id"))
    bill_id                = Column(Integer, ForeignKey("bills.id"), nullable=True)
    travel_date            = Column(Date)
    from_place             = Column(String(100))
    to_place               = Column(String(100))
    mode                   = Column(String(30))
    distance_km            = Column(Float, default=0.0)
    claimed_amount_exc_gst = Column(Float, default=0.0)
    gst_percent            = Column(Float, default=0.0)
    claimed_gst            = Column(Float, default=0.0)
    vendor_state           = Column(String(60))
    vendor_gstin           = Column(String(20))
    bank_state             = Column(String(60))
    bank_gstin             = Column(String(20))
    invoice_date           = Column(Date)
    invoice_number         = Column(String(100))
    no_bill                = Column(Boolean, default=False)
    sanctioned_amount      = Column(Float, default=0.0)
    sanctioned_gst         = Column(Float, default=0.0)
    remarks                = Column(Text)
    created_at             = Column(DateTime, server_default=func.now())

    user  = relationship("User",         back_populates="local_conveyances")
    diary = relationship("MonthlyDiary", back_populates="local_conveyances")
    bill  = relationship("Bill")


class OtherExpense(Base):
    __tablename__ = "other_expenses"
    id                     = Column(Integer, primary_key=True, index=True)
    user_id                = Column(Integer, ForeignKey("users.id"), nullable=False)
    diary_id               = Column(Integer, ForeignKey("monthly_diaries.id"))
    bill_id                = Column(Integer, ForeignKey("bills.id"), nullable=True)
    expense_description    = Column(Text)
    claimed_amount_exc_gst = Column(Float, default=0.0)
    gst_percent            = Column(Float, default=0.0)
    declaration_amount     = Column(Float, default=0.0)
    vendor_state           = Column(String(60))
    vendor_gstin           = Column(String(20))
    bank_state             = Column(String(60))
    bank_gstin             = Column(String(20))
    invoice_date           = Column(Date)
    invoice_number         = Column(String(100))
    claimed_gst            = Column(Float, default=0.0)
    no_bill                = Column(Boolean, default=False)
    sanctioned_amount      = Column(Float, default=0.0)
    sanctioned_gst         = Column(Float, default=0.0)
    remarks                = Column(Text)
    created_at             = Column(DateTime, server_default=func.now())

    user  = relationship("User",         back_populates="other_expenses")
    diary = relationship("MonthlyDiary", back_populates="other_expenses")
    bill  = relationship("Bill")


class Holiday(Base):
    __tablename__ = "holidays"
    id          = Column(Integer, primary_key=True, index=True)
    holiday_date = Column(Date, nullable=False, index=True)
    state       = Column(String(60), nullable=False, index=True)
    description = Column(String(200))
    holiday_type = Column(String(30), default="public")  # public / bank / restricted
    created_at  = Column(DateTime, server_default=func.now())

    __table_args__ = (UniqueConstraint("holiday_date", "state"),)
